WINDOW_WIDTH = 640
WINDOW_HEIGHT = 360
WINDOW_TITLE = "Tennis"

RENDER_TARGET_WIDTH = 320
RENDER_TARGET_HEIGHT = 180

UI_BUTTON_DEFAULT_PADDING = 8

UI_START_BUTTON_TEXT = "Start"
UI_SETTINGS_BUTTON_TEXT = "Settings"
UI_EXIT_BUTTON_TEXT = "Exit"
UI_NEXT_BUTTON_TEXT = "Next"
UI_PREV_BUTTON_TEXT = "Prev"
UI_CONFIRM_BUTTON_TEXT = "Confirm"
UI_PAUSE_OVERLAY_TEXT = "-- PAUSED --"
UI_SELECT_PLAYER_COLOR_TEXT = '-- Select player color --'
UI_SELECT_OPPONENT_COLOR_TEXT = '-- Select opponent color --'

WHITE = { 1, 1, 1, 1 }
BLACK = { 0, 0, 0, 1 }
